Implement Serpentine Helm
geheur/weapon-charges pull request #8
Opened 2022-06-22 06:27 UTC by RHQ-Rusty

This PR lays the groundwork for Barrows Gear implementation (same mechanic as for Serpentine Helm) and also implements the Serpentine Helm, with three variable modes of display: scales, percent, or both. Additionally, the list of tracked weapons was reformatted and updated in the README.

2022-06-22 06:32 UTC, RHQ-Rusty commented on build.gradle
> +	testImplementation 'org.projectlombok:lombok:1.18.4'
Nothing is changed here; unsure of why it's showing like this in the diff. Shows aligned properly in-editor.

2022-06-22 06:37 UTC, RHQ-Rusty commented
Some files also show as having every line changed; this is because I swapped them out (dcbaa015cda4204caa6026a8976f30accec4274a) and swapped them back in (b995fe54bae529ff722cb0121028e6ac4b127d5a). Nothing was changed in them.

2022-06-23 22:11 UTC, geheur requested changes
Some things that didn't fit in any specific place:

I don't like that the percentage thing only applies to the serp helm, it's kind of weird. but I guess it's ok for now.

You changed line endings (I assume based on the giant diffs) on a lot of files, did you really need to do that to get it to run?

The code which tracks charges is ok I guess once it's fixed. There are some weird timing things, at least with ranged attacks, but I cba doing it and I imagine you cba as well.

2022-06-23 22:11 UTC, geheur commented on src/main/java/com/weaponcharges/WeaponChargesPlugin.java
> +		if (hitType != Hitsplat.HitsplatType.VENOM || hitType != Hitsplat.HitsplatType.POISON || hitType != Hitsplat.HitsplatType.HEAL || hitType != Hitsplat.HitsplatType.DISEASE)  {
also a damage_other hitsplat meets the criteria even though it shouldn't. This should be a whitelist not a blacklist.

2022-06-23 22:35 UTC, RHQ-Rusty commented on build.gradle
> +	testImplementation 'org.projectlombok:lombok:1.18.4'
I'm unsure of the white space change; opening both files in an editor yields the same exact display. Perhaps an invisible character?

2022-06-23 22:36 UTC, RHQ-Rusty commented on src/main/java/com/weaponcharges/WeaponChargesItemOverlay.java
> +				} else if (config.serpentine_helm_DisplayMode() == SerpModes.PERCENT) {
Where is the duplication? This is checking what display mode is set, it's a bundle of conditional logic.

2022-06-23 22:37 UTC, RHQ-Rusty commented on src/test/java/com/weaponcharges/ConfigGenerator.java
> +	static int i = -1;
A necessary change to get the updated ConfigGenerator to work. This is tested and causes no issues.

2022-06-23 23:50 UTC, RHQ-Rusty commented
Most of the white-space, line-ending, etc. errors can be attributed to the removal and re-upload of the files; if this is that big of an issue I can recreate the fork and leave the source files as they were. This would only show my changes. Let me know what you would like me to do before I continue with the PR.

2022-06-24 00:01 UTC, closed without merging